name: The static website will be hosted on AWS S3.
on:
  push:
    branches:
      - main
jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configuring the aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION }}
      - name: deploying on s3
        run: |
          aws s3 sync ./ s3://${{vars.BUCKET_NAME}} \
          --exclude "*" \
          --include "index.html"
          



  

